package country
# country/domain script.  All that's stolen is the country database, which was rearranged muchly and looks nothing like the original.  The original is from /usr/share/epic4/scripts
# (C) 1998-2006 Serf <xport525@windstream.net>

alias country (prefix) {
    if ( country[$strip(. $prefix)] ) {return $country[$strip(. $prefix)]} {return Unknown}
} 

alias rcountry {
    foreach country ii {
        if (match(*$0-* $country[$ii])) {
            @ :result #= [.$ii ]
        }
    }
    if (result) {
        if (numwords($result) >= 2) {
            fe ($result) xx {
                cfind $xx
            }
        }
        return $result
    } {
        return Unknown
    }
}

alias cfind (arg) {
    if (left(1 $arg) == [.]) {
        @ :cfind = country($arg)
        xecho_current .$strip(. $arg) is ${cfind? cfind : [Unknown]}
    } {
        @ :cfind = rcountry($arg)
        xecho_current $arg is ${cfind? cfind : [Unknown]}
    }
}
 
@ country[AF] = [Afghanistan]
@ country[AL] = [Albania]
@ country[DZ] = [Algeria]
@ country[AS] = [American Samoa]
@ country[AD] = [Andorra]
@ country[AO] = [Angola]
@ country[AI] = [Anguilla]
@ country[AQ] = [Antarctica]
@ country[AG] = [Antigua and Barbuda]
@ country[AR] = [Argentina]
@ country[AM] = [Armenia]
@ country[AW] = [Aruba]
@ country[AU] = [Australia]
@ country[AT] = [Austria]
@ country[AZ] = [Azerbaijan]
@ country[BS] = [Bahamas]
@ country[BH] = [Bahrain]
@ country[BD] = [Bangladesh]
@ country[BB] = [Barbados]
@ country[BY] = [Belarus]
@ country[BE] = [Belguim]
@ country[BZ] = [Belize]
@ country[BJ] = [Benin]
@ country[BM] = [Bermuda]
@ country[BT] = [Bhutan]
@ country[BO] = [Bolivia]
@ country[BA] = [Bosnia]
@ country[BW] = [Botswana]
@ country[BV] = [Bouvet Island]
@ country[BR] = [Brazil]
@ country[IO] = [British Indian Ocean Territory]
@ country[BN] = [Brunei Darussalam]
@ country[BN] = [Brunei]
@ country[BG] = [Bulgaria]
@ country[BF] = [Burkina Faso]
@ country[BI] = [Burundi]
@ country[BY] = [Byelorussian SSR]
@ country[KH] = [Cambodia]
@ country[CM] = [Cameroon]
@ country[CA] = [Canada]
@ country[CV] = [Cap Verde]
@ country[KY] = [Cayman Islands]
@ country[CF] = [Central African Republic]
@ country[TD] = [Chad]
@ country[CL] = [Chile]
@ country[CN] = [China]
@ country[CX] = [Christmas Island]
@ country[CC] = [Cocos (Keeling) Islands]
@ country[CO] = [Columbia]
@ country[KM] = [Comoros]
@ country[CG] = [Congo]
@ country[CK] = [Cook Islands]
@ country[CR] = [Costa Rica]
@ country[CI] = [Cote D'Ivoire]
@ country[HR] = [Croatia]
@ country[HR] = [Hrvatska]
@ country[CU] = [Cuba]
@ country[CY] = [Cybrus]
@ country[CS] = [Czechoslovakia]
@ country[DK] = [Denmark]
@ country[DJ] = [Djibouti]
@ country[DM] = [Dominica]
@ country[DO] = [Dominican Republic]
@ country[TP] = [East Timor]
@ country[EC] = [Ecuador]
@ country[EG] = [Eqypt]
@ country[SV] = [El Salvador]
@ country[GQ] = [Equatorial Guinea]
@ country[EE] = [Estonia]
@ country[ET] = [Ethiopia]
@ country[FK] = [Falkland Islands]
@ country[FK] = [Malvinas]
@ country[FO] = [Faroe Islands]
@ country[FJ] = [Fiji]
@ country[FI] = [Finland]
@ country[FR] = [France]
@ country[GF] = [French Guiana]
@ country[PF] = [French Polynesia]
@ country[TF] = [French Southern Territories]
@ country[GA] = [Gabon]
@ country[GM] = [Gambia]
@ country[GE] = [Georgia]
@ country[DE] = [Germany]
@ country[DE] = [Deutschland]
@ country[GH] = [Ghana]
@ country[GI] = [Gibraltar]
@ country[GR] = [Greece]
@ country[GL] = [Greenland]
@ country[GD] = [Grenada]
@ country[GP] = [Guadeloupe]
@ country[GU] = [Guam]
@ country[GT] = [Guatemala]
@ country[GN] = [Guinea]
@ country[GW] = [Guinea Bissau]
@ country[GY] = [Gyana]
@ country[HT] = [Haiti]
@ country[HM] = [Heard and Mc Donald Islands]
@ country[HN] = [Honduras]
@ country[HK] = [Hong Kong]
@ country[HU] = [Hungary]
@ country[IS] = [Iceland]
@ country[IN] = [India]
@ country[ID] = [Indonesia]
@ country[IR] = [Iran]
@ country[IQ] = [Iraq]
@ country[IE] = [Ireland]
@ country[IL] = [Israel]
@ country[IT] = [Italy]
@ country[JM] = [Jamaica]
@ country[JP] = [Japan]
@ country[JO] = [Jordan]
@ country[KZ] = [Kazakhstan]
@ country[KE] = [Kenya]
@ country[KI] = [Kiribati]
@ country[KP] = [North Korea]
@ country[KR] = [South Korea]
@ country[KW] = [Kuwait]
@ country[KG] = [Kyrgyzstan]
@ country[LA] = [Lao]
@ country[LA] = [Laos]
@ country[LV] = [Latvia]
@ country[LB] = [Lebanon]
@ country[LS] = [Lesotho]
@ country[LR] = [Liberia]
@ country[LY] = [Libyan Arab Jamahiriya]
@ country[LY] = [Lybia]
@ country[LI] = [Liechtenstein]
@ country[LT] = [Lituania]
@ country[LU] = [Luxembourg]
@ country[MO] = [Macau]
@ country[MK] = [Macedonia]
@ country[MG] = [Madagascar]
@ country[MW] = [Malawi]
@ country[MY] = [Malaysia]
@ country[MV] = [Maldives]
@ country[ML] = [Mali]
@ country[MT] = [Malta]
@ country[MH] = [Marshall Islands]
@ country[MQ] = [Martinique]
@ country[MR] = [Mauritania]
@ country[MU] = [Mauritius]
@ country[MX] = [Mexico]
@ country[FM] = [Micronesia]
@ country[MD] = [Moldova]
@ country[MC] = [Monaco]
@ country[MN] = [Mongolia]
@ country[MS] = [Montserrat]
@ country[MA] = [Morocco]
@ country[MZ] = [Mozambique]
@ country[MM] = [Myanmar]
@ country[NA] = [Namibia]
@ country[NR] = [Nauru]
@ country[NP] = [Nepal]
@ country[NL] = [Netherlands]
@ country[AN] = [Netherlands Antilles]
@ country[NT] = [Neutral Zone]
@ country[NC] = [New Caledonia]
@ country[NZ] = [New Zealand]
@ country[NI] = [Nicaragua]
@ country[NE] = [Niger]
@ country[NG] = [Nigeria]
@ country[NU] = [Niue]
@ country[NF] = [Norfolk Island]
@ country[MP] = [Northern Mariana Islands]
@ country[NO] = [Norway]
@ country[OM] = [Oman]
@ country[PK] = [Pakistan]
@ country[PW] = [Palau]
@ country[PA] = [Panama]
@ country[PG] = [Papua New Guinea]
@ country[PG] = [Papua]
@ country[PG] = [New Guinea]
@ country[PY] = [Paraguay]
@ country[PE] = [Peru]
@ country[PH] = [Philippines]
@ country[PN] = [Pitcairn]
@ country[PL] = [Poland]
@ country[PT] = [Portugal]
@ country[PR] = [Puerto Rico]
@ country[QA] = [Qatar]
@ country[RE] = [Reunion]
@ country[RO] = [Romania]
@ country[RU] = [Russian Federation]
@ country[RW] = [Rwanda]
@ country[KN] = [Saint Kitts and Nevis]
@ country[LC] = [Saint Lucia]
@ country[VC] = [Saint Vincent and the Grenadines]
@ country[WS] = [Samoa]
@ country[SM] = [San Marino]
@ country[ST] = [Sao Tome and Principe]
@ country[SA] = [Saudi Arabia]
@ country[SN] = [Senegal]
@ country[SC] = [Seychelles]
@ country[SL] = [Sierra Leone]
@ country[SG] = [Singapore]
@ country[SI] = [Slovania]
@ country[SB] = [Solomon Islands]
@ country[SO] = [Somalia]
@ country[ZA] = [South Africa]
@ country[ES] = [Spain]
@ country[LK] = [Sri Lanka]
@ country[SH] = [St. Helena]
@ country[PM] = [St. Pierre and Miquelon]
@ country[SD] = [Sudan]
@ country[SR] = [Suriname]
@ country[SJ] = [Svalbard and Jan Mayen Islands]
@ country[SZ] = [Swaziland]
@ country[SE] = [Sweeden]
@ country[CH] = [Switzerland]
@ country[CH] = [Cantons of Helvetia]
@ country[CH] = [Confederation Helvetique]
@ country[SY] = [Syrian Arab Republic]
@ country[SY] = [Syria]
@ country[TW] = [Taiwan]
@ country[TJ] = [Tajikistan]
@ country[TZ] = [Tanzania]
@ country[TH] = [Thailand]
@ country[TG] = [Togo]
@ country[TK] = [Tokelau]
@ country[TO] = [Tonga]
@ country[TT] = [Trinidad and Tobago]
@ country[TN] = [Tunisia]
@ country[TR] = [Turkey]
@ country[TM] = [Turkmenistan]
@ country[TC] = [Turks and Caicos Islands]
@ country[TV] = [Tuvalu]
@ country[UG] = [Uganda]
@ country[UA] = [Ukranian SSR]
@ country[AE] = [United Arab Emirates]
@ country[UK] = [United Kingdom]
@ country[GB] = [Great Britain]
@ country[US] = [United States of America]
@ country[US] = [United States]
@ country[UM] = [Unites States Minor Outlying Islands]
@ country[UY] = [Uruguay]
@ country[SU] = [USSR]
@ country[SU] = [Soviet Union]
@ country[UZ] = [Uzbekistan]
@ country[VU] = [Vanuatu]
@ country[VA] = [Vatican]
@ country[VA] = [Vatican City State]
@ country[VE] = [Venezuela]
@ country[VN] = [Viet Nam]
@ country[VI] = [Virgin Islands (US)]
@ country[VG] = [Virgin Islands (UK)]
@ country[WF] = [Wallis and Futuna Islands]
@ country[EH] = [Western Sahara]
@ country[YE] = [Yemen]
@ country[YU] = [Yugoslavia]
@ country[ZR] = [Zaire]
@ country[ZM] = [Zambia]
@ country[ZW] = [Zimbabwe]
@ country[COM] = [US Commercial]
@ country[EDU] = [US Educational]
@ country[NET] = [Network]
@ country[MIL] = [U.S. Military]
@ country[ORG] = [Non-Profit Organization]
@ country[GOV] = [Government (US)]
@ country[KP] = [Korea - Democratic People's Republic of]
@ country[KR] = [Korea - Republic Of]
@ country[LA] = [Lao People's Democratic Republic]
@ country[SK] = [Slovakia]
